[package]
name = "liz"
version = "0.1.0"
edition = "2021"

[dependencies]
cpal = { version = "0.15.3" }
anyhow = "1.0.89"
whisper-rs = "0.11.1"
time = "0.3.36"
ratatui = "0.28.1"
crossterm = "0.28.1"
clipboard-rs = "0.2.1"

[[bin]]
name = "liz"
path = "src/screen.rs"
